version: 3

vars:
  BINARY: docker-init
  INSTALL_PATH: $HOME/.docker-init
  CLI_PLUGIN_PATH: $HOME/.docker/cli-plugins

tasks:
  build:
    # deps:
    #   - test
    cmds:
      - go build -v .

  test:
    cmds:
      - go test -v ./... -cover

  install:
    deps:
      - build
    cmds:
      # Install the templates
      - mkdir -p {{.INSTALL_PATH}}
      - ln -sf $PWD/templates {{.INSTALL_PATH}}/templates

      # Install the CLI plugin
      - mkdir -p {{.CLI_PLUGIN_PATH}}
      - ln -sf $PWD/{{.BINARY}} {{.CLI_PLUGIN_PATH}}

  uninstall:
    cmds:
      - rm -rf {{.INSTALL_PATH}}
      - rm -rf {{.CLI_PLUGIN_PATH}}/{{.BINARY}}

  clean:
    cmds:
      - go clean
